apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    component: mysql
    project: expense
    tire: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tire: db
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tire: db
    spec:
      containers:
      - name: mysql
        image: rammohan855/mysql:latest

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tire: db
  ports:
  - protocal: TCP
    port: 3306 # service port
    targetPort: 3306 # target port