apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    component: mysql
    project: expense
    tire: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tire: db
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tire: db
    spec:
      containers:
      - name: mysql
        image: rammohan855/mysql:latest