apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: DevOps
    trainer: ram
  annotations:
    kubernetes.io/created-by: 'ram'
    jenkins.build.url: 'https://jenkins/expense/job'
spec:
  containers:
  - name: nginx
    image: nginx