apiVersion: v1
kind: Pod
metadata:
  name: nginx-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course-1
      valueFrom:
        configMapKeyRef:
          name: config-example
          key: course

    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: config-example
          key: trainer
    
