apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  seector:
    name: frontend
    project: robo
    component: backend
    enveronment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80